import re

with open("frontend/src/app/page.tsx", "r") as f:
    text = f.read()

text = text.replace(
    "SalesBrain Navigator processes your retail data locally within the environment. We do not transmit PII. Access to the ML API is governed by strict IAM roles.",
    "SalesBrain Navigator processes uploaded datasets through its authenticated backend analytics pipeline and stores workspace data in configured persistent storage. Authenticated access and per-user workspace isolation protect workspace operations."
)

text = text.replace(
    "Automated anomaly detection, risk flagging, and prescriptive recommendations generated by our ML pipeline.",
    "Rule-based data insights, risk flagging, and prescriptive recommendations alongside ML-powered profit prediction."
)

text = text.replace(
    "Role-Based Access Control",
    "Authenticated Access & Tenant Isolation"
)

text = text.replace(
    "Get ML Insights",
    "Generate Data Insights & Profit Predictions"
)

with open("frontend/src/app/page.tsx", "w") as f:
    f.write(text)

